# syntax docker/dockerfile:1

FROM node:16.6

WORKDIR /app

RUN mkdir -p /app/data

COPY ["package.json", "./"]

RUN npm install

COPY . .

ARG APPLICATION_ID
ARG BOT_TOKEN
ARG COMMANDS_DIR
ARG FEATURES_DIR
ARG COMPETITION_CHANNEL_ID
ARG COMPETITION_CHANNEL_NAME
ARG COMPETITION_WEEKLY_POST_ID
ARG COMPETITION_SEASON_POST_ID
ARG DATA_BACKUPS_CHANNEL_ID
ARG DISCORD_BASE_API
ARG GUILD_ID
ARG SECONDS_TO_DELETE_MESSAGE
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG BOT_OWNER

ENV APPLICATION_ID $APPLICATION_ID
ENV BOT_TOKEN $BOT_TOKEN
ENV COMMANDS_DIR $COMMANDS_DIR
ENV FEATURES_DIR $FEATURES_DIR
ENV COMPETITION_CHANNEL_ID $COMPETITION_CHANNEL_ID
ENV COMPETITION_CHANNEL_NAME $COMPETITION_CHANNEL_NAME
ENV COMPETITION_WEEKLY_POST_ID $COMPETITION_WEEKLY_POST_ID
ENV COMPETITION_SEASON_POST_ID $COMPETITION_SEASON_POST_ID
ENV DATA_BACKUPS_CHANNEL_ID $DATA_BACKUPS_CHANNEL_ID
ENV DISCORD_BASE_API $DISCORD_BASE_API
ENV GUILD_ID $GUILD_ID
ENV SECONDS_TO_DELETE_MESSAGE $SECONDS_TO_DELETE_MESSAGE
ENV DB_NAME $DB_NAME
ENV DB_USER $DB_USER
ENV DB_PASSWORD $DB_PASSWORD
ENV BOT_OWNER $BOT_OWNER

CMD [ "node", "index.js" ]
